### ISSUE TITLE
Is their a way to generate anml file by using VASim tool ?

### ISSUE THREAD

**Issue by Maryom** [jackwadden/VASim#24]
Hi,

Thanks for your efforts. My AP key is expired, until know I'm able to generate anml file from python script in the machine that has all dependencies before the key is expired. However, I need to use new machine that don't have AP installed before. In the new machine I tried to install python binding by running the following command:

`apt-get install ap-python`

I got the following error:

`E: Unable to locate package ap-python`

Any idea how to install it ? No need for APWorkbenchI I just need to generate anml from python script.

Is their a way to generate anml file by using VASim tool ?
 
Thanks.

**Comment by jackwadden** [comment]
There is not. VASim does not have python bindings, but you can use VASim as a library to programmatically build automata in C++. Take a look at the README and also the tests folder to see some examples of how to do this.

If you need to use python, I would suggest either writing your own python functions to emit ANML XML, or us the [MRNL library](https://github.com/kevinaangstadt/mnrl) to generate hStates. hStates are identical to STEs and can be parsed by VASim. VASim can also simulate MNRL hState networks and emit the corresponding ANML if you need ANML.

**Comment by Maryom** [comment]
Ok thanks.
