### ISSUE TITLE
dump-state print files

### ISSUE THREAD

**Issue by karakchi** [jackwadden/VASim#25]
Hi Jack, 
What <int> means in dump-state debug? and what are you trying to print in stes_<cycle>.states files? 
Is it only self-loops? Thanks,

**Comment by jackwadden** [comment]
"Dump state" is meant for debugging purposes. It "dumps" all activated states to a file during a specified cycle. This allows you to peak inside of the execution core of VASim without setting breakpoints etc...

Let me know if you need extra functionality or if the dump-state flag isn't working. That flag actually no longer prints the special element activity. I'll update the usage to be clearer.

**Comment by karakchi** [comment]
Sure,I'll let you know if I need extra functionality, Thanks Jack!
