### ISSUE TITLE
Incorrect Error Message

### ISSUE THREAD

**Issue by tjt7a** [jackwadden/VASim#3]
When I call vasim with the following parameters, I get an erroneous error message:
vasim -t 1 -a model.anml

message:
"Could not load .xml file: 1"

I should have used the -T argument, but this error message is not helpful.

**Comment by jackwadden** [comment]
-t is a legal option, and it is possible to have an anml file named "1". I think this is a fine error message as it was not able to find the anml file you accidentally specified as input.

**Comment by karakchi** [comment]
Hi, 
I got same error "Could not load .xml file: test", when I use anml to nfa using 
./vasim -n test anml_file_name. 

Test is output nfa file I want to generate. 
Also there is automata_0.nfa generated inside vasim I don't know if it is relating to this command, but it's NFAs  different than what I should get from anml file. 

Any help??

**Comment by jackwadden** [comment]
The -n option does not take a file name argument, and VASim reads the first non-option argument as the ANML input file.

$ vasim -n anml_file_name

....should work. This will emit the NFA in the iNFAnt/Becchi format as automata_0.nfa.

**Comment by karakchi** [comment]
Hi Jack, 

Thank you for the reply, 
when I run ./vasim -n ../vasim/ANMLZoo/Snort/anml/snort.1chip.anml, I got segmentation fault as shown below, also automata_0.nfa not changed still seeing same NFAs as in Michela/ test2.re 

|------------------------|
|     Parsing  Input     |
|------------------------|

|------------------------|
|      Parsing  ANML     |
|------------------------|
Building automata from file: /share/reconfig/vasim/ANMLZoo/Snort/anml/snort.1chip.anml
Automata Statistics
  Elements: 69737
  STEs: 69029
  SpecialElements: 708
  Max Fan-in (not including self loops): 19
  Max Fan-out (not including self loops): 19
  Average Node Degree: 1.11009

Finding distinct subgraphs...
  Found 2585 distinct subgraphs!

Combining 2585 distinct subgraphs into 1 graphs...

**Segmentation fault (core dumped)**

**Comment by karakchi** [comment]
Also, I see automata_0.nfa style generated little different that michela NFAs style. 
Michlea NFA  shows the state and its transitions as below,  but  automata_0.nfa is edges and labels 
Is there anyway to get same .nfa style as Michela's using VASIM ? 

- state 0
  + transitions:: (0,3)(255,3)(254,3)(253,3)(252,3)(251,3)(250,3)(249,3)(248,3)(247,3)(246,3)(245,3)(244,3)(243,3)(242,3)(241,3)(240,3)(239,3)(238,3)(237,3)(236,3)(235,3)(234,3)(233,3)(232,3)(231,3)(230,3)(229,3)(228,3$
- state 1
  accepts: 96   + transitions::
- state 2
  + transitions:: (1,52)(57,2)(56,2)(55,2)(54,2)(53,2)(52,2)(51,2)(50,2)(49,2)(48,2)(45,51)(32,50)(32,53)(13,50)(13,53)(12,50)(12,53)(10,50)(10,53)(9,50)(9,53)
- state 3
  + transitions:: (0,3)(255,3)(254,3)(253,3)(252,3)(251,3)(250,3)(249,3)(248,3)(247,3)(246,3)(245,3)(244,3)(243,3)(242,3)(241,3)(240,3)(239,3)(238,3)(237,3)(236,3)(235,3)(234,3)(233,3)(232,3)(231,3)(230,3)(229,3)(228,3$
- state 4
  + transitions:: (8,64)(12,64)

**Comment by jackwadden** [comment]
> when I run ./vasim -n ../vasim/ANMLZoo/Snort/anml/snort.1chip.anml, I got segmentation fault as shown below, also automata_0.nfa not changed still seeing same NFAs as in Michela/ test2.re

Because snort has Special Elements (OR logic gates), which are not supported in the theoretical NFA model, you must remove them first using the -x option. Note that this does not change functionality of the automata (if implemented correctly!) because OR gates are redundant.

I will push a commit soon to provide a helpful error message.

> Also, I see automata_0.nfa style generated little different that michela NFAs style.
> Michlea NFA shows the state and its transitions as below, but automata_0.nfa is edges and labels
> Is there anyway to get same .nfa style as Michela's using VASIM ?

This is a different style from the version of her tools I'm using. If you can send me a specification and cc Prof. Becchi or student who was responsible for defining that automata format, I'd be happy to add it. Alternatively, you are welcome to fork VASim, build the emitter in the style of Automata::automataToNFA(...), and submit a pull request.

Let me know if you have any other questions, and feel free to submit other issues as you run into them!

**Comment by jackwadden** [comment]
I've fixed this error in commit 50a89ba. In the future, please open a new issue ticket for unrelated issues.
