### ISSUE TITLE
multi threading core dumped

### ISSUE THREAD

**Issue by karakchi** [jackwadden/VASim#32]
Hello Jack, 

When I run ANMLZoo using multithreading -T, I get floating point exception (core dumped), what is the reason for that? 

Another question: VASIM prints #subgraphs among 1 thread, is there any way I can get #subgraphs in each thread (in case I use multithreading) and know specifically what the sub graphs are ? 

Thanks, 
Rasha

**Comment by jackwadden** [comment]
> When I run ANMLZoo using multithreading -T, I get floating point exception (core dumped), what is the reason for that?
Could you send me the exact command line arguments you used and (if willing) the automata and input files you're passing in?

> Another question: VASIM prints #subgraphs among 1 thread, is there any way I can get #subgraphs in each thread (in case I use multithreading) and know specifically what the sub graphs are ?
I can certainly do this, but it should be easy to calculate by hand. VASim just distributes the subgraphs round-robin to available parallel threads. So if you have 10 subgraphs and 4 threads, 2 threads will have three subgraphs and 2 threads will have two subgraphs.

Let me know if you'd like me to add more statistics to the print out though.

-Jack

**Comment by karakchi** [comment]
Hi Jack, 

Thank you for the reply, 

Regarding to my first question, I found the problem that if I write T 2 works , but T=2 core dumped 
Second question, I am thinking if I can know what the subgraphs are per each thread like T1 subgrahps (NFAs)  are state 1->2->3->4,

**Comment by jackwadden** [comment]
I think adding -a to your vasim options will work for you. -a dumps the automata subgraphs passed to each thread as a separate file "automata_<thread_num>.anml. You can just examine each file after the run in order to get the mapping. Let me know if this doesn't help, I'm happy to make changes.
