### ISSUE TITLE
using -i 

### ISSUE THREAD

**Issue by karakchi** [jackwadden/VASim#33]
Hello Jack, 

I am trying to use input strings instead of the input files to produce the reports. 
I am writing it in this way ./vasim -i -r *.anml "string"  , however, I get reports and time both 0.  

Is this the correct way to use -i? 

I would appreciate it  if you can, write me any example relating to this. 

Thanks, 
Rasha

**Comment by jackwadden** [comment]
Rasha,

You should be able to do './vasim -r automata.anml -i "my input string"'. If there is different behavior between -i input and input from a file, send me the input and file and I can debug.

-Jack

**Comment by karakchi** [comment]
Hi Jack, 

Yes, I was able to run this command, I found where my mistake was. 
Sorry for the late reply, 

Thank you,
