### ISSUE TITLE
report cycles

### ISSUE THREAD

**Issue by karakchi** [jackwadden/VASim#36]
Hello Jack, 

When I type -r, report file is generated containing three columns. 
For verification, is the sequence of the columns offset:report_STE:cycles or cycles:stes:offset? 

Thanks,

**Comment by jackwadden** [comment]
The -r output format is <cycle>:<STE ID>:<report code>.

Cycle is the index into the symbol stream where the report was triggered. STE ID is the string ID of the STE that triggered. Report code is a separate code that is optionally associated with reports. Report codes are usually used for things like classification, e.g. if multiple reporting STEs report with different character classes but "mean the same thing".
